//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmostSurely.Utilities.Console.AlmostSurelyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlmostSurelyServiceReference.IAlmostSurelyService")]
    public interface IAlmostSurelyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlmostSurelyService/GetNewImages", ReplyAction="http://tempuri.org/IAlmostSurelyService/GetNewImagesResponse")]
        void GetNewImages(object container);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlmostSurelyService/GetNewImages", ReplyAction="http://tempuri.org/IAlmostSurelyService/GetNewImagesResponse")]
        System.Threading.Tasks.Task GetNewImagesAsync(object container);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlmostSurelyServiceChannel : AlmostSurely.Utilities.Console.AlmostSurelyServiceReference.IAlmostSurelyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmostSurelyServiceClient : System.ServiceModel.ClientBase<AlmostSurely.Utilities.Console.AlmostSurelyServiceReference.IAlmostSurelyService>, AlmostSurely.Utilities.Console.AlmostSurelyServiceReference.IAlmostSurelyService {
        
        public AlmostSurelyServiceClient() {
        }
        
        public AlmostSurelyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmostSurelyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmostSurelyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmostSurelyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetNewImages(object container) {
            base.Channel.GetNewImages(container);
        }
        
        public System.Threading.Tasks.Task GetNewImagesAsync(object container) {
            return base.Channel.GetNewImagesAsync(container);
        }
    }
}
